# Dataset

- **Invoice ID**: Unique identifier for each transaction.
- **Branch**: The branch location of the supermarket (e.g., Yangon, Naypyitaw, Mandalay).
- **City**: The city in which the supermarket branch is located.
- **Customer Type**: Indicates whether the customer is a 'Member' or 'Normal'.
- **Gender**: Gender of the customer.
- **Product Line**: The category of the product sold (e.g., Health & Beauty, Electronic Accessories, Home & Lifestyle).
- **Unit Price**: Price per unit of the product.
- **Quantity**: Number of items purchased.
- **Tax 5%**: Calculated tax amount on the transaction at a 5% rate.
- **Sales**: Total amount for the transaction including tax.
- **Date**: Date of the transaction.
- **Time**: Time of the transaction.
- **Payment**: Payment method used (e.g., Cash, Ewallet, Credit card).
- **COGS**: Cost of goods sold, representing the raw cost of the products.
- **Gross Margin Percentage**: Fixed percentage of profit for each sale (4.7619%).
- **Gross Income**: Profit earned from the transaction.
- **Rating**: Customer satisfaction rating (out of 10).

# Data Preparation

In [65]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import chardet
import warnings
warnings.filterwarnings("ignore")

import os
for dirname, _, filenames in os.walk("./dataset"):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./dataset\Supermarket Analysis - Excel.xlsx
./dataset\SuperMarket Analysis.csv

In [66]:
with open("./dataset/SuperMarket Analysis.csv", "rb") as f:
    print(chardet.detect(f.read()))

{'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}

In [67]:
df = pd.read_csv("./dataset/SuperMarket Analysis.csv")

In [68]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [70]:
df.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(0)

## Data Wrangling

In [72]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# Data Understanding

In [73]:
df.describe()

,Unit price,Quantity,Tax 5%,Sales,Date,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,2019-02-14 00:05:45.600000,307.58738,4.761905,15.379369,6.97270
min,10.080000,1.000000,0.508500,10.678500,2019-01-01 00:00:00,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,2019-01-24 00:00:00,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,2019-02-13 00:00:00,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,2019-03-08 00:00:00,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,2019-03-30 00:00:00,993.00000,4.761905,49.650000,10.00000
std,26.494628,2.923431,11.708825,245.885335,NaN,234.17651,0.000000,11.708825,1.71858

> Data tidak memiliki outlier berarti. Outlier yang ada pada sales dan cogs, terbilang normal untuk sebuah data penjualan. Karena seorang customer bisa saja belanja dalam jumlah besar dalam sekali transaksi.

In [74]:
df.describe(include="object").T

              count unique                  top freq
Invoice ID     1000   1000          849-09-3807    1
Branch         1000      3                 Alex  340
City           1000      3               Yangon  340
Customer type  1000      2               Member  565
Gender         1000      2               Female  571
Product line   1000      6  Fashion accessories  178
Time           1000    506           7:48:00 PM    7
Payment        1000      3              Ewallet  345

> Secara keseluruhan, dataset tidak memiliki missing value, tidak ada data duplikasi, namun memiliki outlier yang aman dalam data penjualan.

In [75]:
summary = pd.DataFrame({
    "Metric": [
        "Total Transaksi",
        "Total Sales",
        "Rata rata Sales per Transaksi",
        "Total Gross Income",
        "Rata rata Gross Income per Transaksi",
        "Jumlah City",
        "Jumlah Kategori Produk",
        "Jumlah Customer Type",
        "Jumlah Payment"
    ],
    "Value": [
        df["Invoice ID"].count(),
        df["Sales"].sum(),
        df["Sales"].mean(),
        df["gross income"].sum(),
        df["gross income"].mean(),
        df["City"].nunique(),
        df["Product line"].nunique(),
        df["Customer type"].nunique(),
        df["Payment"].nunique()
    ]
})

summary["Value"] = summary["Value"].apply(
    lambda x: round(x, 2) if isinstance(x, (int, float)) else x
)

summary

                                 Metric      Value
0                       Total Transaksi    1000.00
1                           Total Sales  322966.75
2         Rata rata Sales per Transaksi     322.97
3                    Total Gross Income   15379.37
4  Rata rata Gross Income per Transaksi      15.38
5                           Jumlah City       3.00
6                Jumlah Kategori Produk       6.00
7                  Jumlah Customer Type       2.00
8                        Jumlah Payment       3.00

In [76]:
fig = px.histogram(
    df["Sales"],
    nbins=50
)

fig.update_traces(
    marker_line_width=1,
    marker_line_color="black"
)

fig.show()

In [77]:
fig = px.box(
    df["Sales"]
)
fig.show()

# Exploratory Data Analysis

In [98]:
file_path = r'.\dataset\Supermarket Analysis - Excel.xlsx'
os.system(f'start excel "{file_path}"')

0

# Dashboard

https://datastudio.google.com/reporting/65df8127-06d6-4863-be25-90183c816e48